"""Fix the type of fields

Revision ID: 47f91801e4fe
Revises: 75e8ab9a0014
Create Date: 2020-12-16 01:27:27.311433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "47f91801e4fe"
down_revision = "75e8ab9a0014"
branch_labels = None
depends_on = None


def upgrade():
    print("hello")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dynamic_challenge", sa.Column("decrease", sa.Float(), nullable=True))
    op.add_column("dynamic_challenge", sa.Column("slope", sa.Float(), nullable=True))
    op.drop_column("dynamic_challenge", "minimum")
    op.drop_column("dynamic_challenge", "decay")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dynamic_challenge", sa.Column("decay", sa.INTEGER(), nullable=True))
    op.add_column(
        "dynamic_challenge", sa.Column("minimum", sa.INTEGER(), nullable=True)
    )
    op.drop_column("dynamic_challenge", "slope")
    op.drop_column("dynamic_challenge", "decrease")
    # ### end Alembic commands ###
